# Generated by Django 2.1.3 on 2018-11-18 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Requer 15 caracteres ou menos', max_length=15, unique=True, verbose_name='usuario')),
                ('password', models.CharField(help_text='Digite uma senha com 15 caracteres ou menos', max_length=15, verbose_name='senha')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, help_text='Designado para usuarios admin', verbose_name='Status de staff')),
                ('is_active', models.BooleanField(default=False, help_text='Designado para usuários ativos. \\ Em vez de deletar, desative o mesmo.', verbose_name='active')),
                ('is_student', models.BooleanField(default=False, help_text='Designado para usuarios do tipo Aluno', verbose_name='Aluno')),
                ('is_orientador', models.BooleanField(default=False, help_text='Designado para usuarios do tipo Orientador', verbose_name='Orientador')),
                ('is_supervisor', models.BooleanField(default=False, help_text='Designado para usuarios do tipo Supervisor', verbose_name='Supervisor')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de ingresso')),
                ('is_trusty', models.BooleanField(default=False, help_text='Usuários com contas confirmadas.', verbose_name='Email confirmado')),
                ('matricula', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
